require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

-- 插件
require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/autopairs")
require("plugins/comment")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/telescope")
require("plugins/smoothcursor")
require("plugins/neoscroll")
require("plugins/mini-map")
require("plugins/lazygit")
require("plugins/filetype")
require("plugins/lastplace")
require("plugins/startup")
require("plugins/outline")
require("plugins/barbecue")
require("plugins/telescope-file-browser")
